#!/usr/bin/env bash

killall -q STcontrol_eudaq
killall -q euCliProducer
killall -q euCliCollector
killall -q StdEventMonitor
killall -q euLog
killall -q euRun
killall -q xterm
xterm -T "remote killing" -e "ssh -X testbeam@192.168.22.100 'killall -q euCliProducer; killall -q euCliCollector'" &

sleep 1

xterm -T "Run Control" -e 'euRun' &
sleep 2 

xterm -T "Collector" -e 'euCliCollector -n TriggerIDSyncDataCollector -t one_dc -r tcp://192.168.22.1' &
sleep 1

xterm -T "EUDET TLU Producer" -e 'euCliProducer -n EudetTluProducer -t eudet_tlu -r tcp://192.168.22.1' & 
xterm -T "NI/Mimosa Producer" -e 'euCliProducer -n NiProducer -t ni_mimosa -r tcp://192.168.22.1' &
sleep 1

xterm -T "FE-I4" -e 'echo "wS08071919" | sudo -S env LD_LIBRARY_PATH=$LD_LIBRARY_PATH /opt/STcontrol_5.3/bin/STcontrol_eudaq -r 192.168.22.1 -s' &
sleep 1

xterm -T "Online Monitor" -e 'StdEventMonitor -t StdEventMonitor -r tcp://192.168.22.1' & 


xterm -T "ALPIDE 0" -e "ssh -X testbeam@192.168.22.100 'cd /home/testbeam/alpide/soft_install/bin && ./euCliProducer -n JadeProducer -t alpide_0 -r tcp://192.168.22.1'" & 
xterm -T "ALPIDE 1" -e "ssh -X testbeam@192.168.22.100 'cd /home/testbeam/alpide/soft_install/bin && ./euCliProducer -n JadeProducer -t alpide_1 -r tcp://192.168.22.1'" & 

